# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
    ]
